version: "3.1"
services:
  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=dbUser"
      - "POSTGRES_PASSWORD=dbPassword"
      - "POSTGRES_DB=Splitter"