
splitter:
  rollen:
    organisator: souhaib101, ajaw3

server:
  port: 9000
spring:
  datasource:
    username: dbUser
    password: dbPassword
    url: jdbc:postgresql://localhost:5432/Splitter


  flyway:
    user: dbUser
    password: dbPassword
    url: jdbc:postgresql://localhost:5432/Splitter

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            authorization-grant-type: authorization_code
            scope: user
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token