server:
  port: 9000
spring:
  datasource:
    username: dbUser
    password: dbPassword
    url: jdbc:postgresql://localhost:5432/Splitter

  flyway:
    user: dbUser
    password: dbPassword
    url: jdbc:postgresql://localhost:5432/Splitter
    schemas: Splitter
    create-schemas: true